export const ALLERGENS = [
  { code: 'PNUT', name: 'Peanut' },
  { code: 'MILK', name: 'Milk / Dairy' },
  { code: 'EGG',  name: 'Egg' },
  { code: 'WHEAT', name: 'Wheat' },
  { code: 'SOY',  name: 'Soy' },
  { code: 'SES',  name: 'Sesame' },
  { code: 'FISH', name: 'Fish' },
  { code: 'CRUST', name: 'Shellfish' },
  { code: 'MOLL', name: 'Molluscs' },
  { code: 'TNUT', name: 'Tree nuts' },
  { code: 'MUST', name: 'Mustard' },
  { code: 'SULF', name: 'Sulphites' },
  { code: 'CEL',  name: 'Celery' },
  { code: 'LUP',  name: 'Lupin' },
  { code: 'RYE',  name: 'Rye' },
  { code: 'OAT',  name: 'Oats' },
  { code: 'BAR',  name: 'Barley' },
  { code: 'SPELT', name: 'Spelt' },
  { code: 'KAMU', name: 'Kamut' },
  { code: 'LATEX', name: 'Latex' },
  { code: 'CORN', name: 'Corn' },
]
